#!/usr/bin/env python
# 
# Gets a random username and prints it to standard output

import urllib.request
import re
import sys

# Use the url for getting a random list
url = "http://myanimelist.net/users.php?lucky=1"
f = urllib.request.urlopen(url)

# Extract the username from the title
usernameRegex = r"<title>([\S]+)'s Anime List - MyAnimeList.net</title>"
match = re.search(usernameRegex, f.read().decode())

if match is None:
	print("Error: No regular expression match", file = sys.stderr)
	exit(1)
	
print(match.group(1))